import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import {useState, useEffect} from 'react';
import {Card, Button, Input, Form} from 'semantic-ui-react';

export default function Home({ client }) {
  const [inputValue, setInputValue] = useState({ idClient: "" });
  const [idValid, setIdValid] = useState(true);
  
  let arrIdClients = [];
  for (let i = 0; i < client.length; ++i) {
    arrIdClients.push(client[i].idClient);
  }
    
  function handleKeyPress(e) {
    setInputValue({idClient: e.target.value});
  }

  useEffect(() => {
    if (isNaN(inputValue.idClient) === false) {
      setIdValid(true);
    } else {
      setIdValid(false);
    }
  }, [inputValue.idClient]);

  return (
    <div className={styles.container}>
      <Head>
        <title>HR Clinic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card>
        <Card.Content>
          <h3>Selectie ID client</h3>
          <Card.Description>
            <Form>
              <Form.Field>
                <label>ID Client</label>
                <input placeholder='ID Client' type='text' value={inputValue.idClient} onChange={handleKeyPress} />
              </Form.Field>
            </Form>
          </Card.Description>
          {idValid 
              ? 
              null 
              : 
              <p>ID-ul trebuie sa fie numeric!</p>
            }
        </Card.Content>
        {idValid
            ?
            <Card.Content >
              <div className='ui two buttons'>
                <Link href={{ pathname: "/account", query: inputValue }}>
                  <Button color="green">Submit</Button>
                </Link> 
              </div>
            </Card.Content>
            :
            <Card.Content >
              <div className='ui two buttons'>
                <Button color="green">Submit</Button> 
              </div>
            </Card.Content>
          }
      </Card>
    </div>
  )
}

Home.getInitialProps = async () => {
  const res = await fetch('http://localhost:3000/api');
  const { data } = await res.json();

  return { client: data }
}